import Link from "next/link";

export const metadata = {
  title: "Arthur NextJS with Dea Afrizal",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: "Arial",
        }}
      >
        <nav
          style={{
            padding: 10,
            margin: 8,
          }}
        >
          <Link
            href="/"
            style={{
              padding: "0 10px 0 0",
            }}
          >
            Home
          </Link>
          <Link
            href="/Posts"
            style={{
              padding: "0 10px 0 0",
            }}
          >
            Posts
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
